#!/bin/bash

basename='file_basename'

# fasta file generated by flair can be used as the equivalent of a transcriptome fasta - make salmon index with this
salmon index -t collapse_new_10p_filtered_named.isoforms.fa -i flair_salmon_index

# run salmon in quant mode using Illumina paired end reads
salmon quant -i flair_salmon_index -l ISF --gcBias -1 ${basename}_Illumina_R2.fastq.gz -2 ${basename}_Illumina_R1.fastq.gz --validateMappings -p 4 -o $basename

# get TPMs from salmon quant file using SUPPA script
multipleFieldSelection.py -i ./${basename}/quant.sf -k 1 -f 4 -o ${basename}_iso_tpm.txt